# -*- coding: utf-8 -*-
"""brain_tumour_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKYThSRM_97YXmaOM0GiLWWpJCfX89Qh
"""

!pip install -q "numpy<2.0" monai==1.3.2 nibabel gdown SimpleITK einops tqdm scikit-image matplotlib scipy opencv-python-headless

import numpy as np
print("NumPy version:", np.__version__)
assert np.__version__.startswith("1."), "NumPy 2.x detected — restart the runtime after installing numpy<2.0"

import os
import glob
import random
import re
import threading

import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR

from tqdm import tqdm

from monai.transforms import (
    Compose,
    RandFlipd,
    RandRotate90d,
    RandGaussianNoised,
    RandAdjustContrastd,
    RandShiftIntensityd,
)

from monai.losses import DiceCELoss
from monai.networks.nets import SwinUNETR

from sklearn.model_selection import train_test_split

import numpy
import torch
import monai

print("NumPy :", numpy.__version__)
print("Torch :", torch.__version__)
print("MONAI :", monai.__version__)

import importlib

libs = ["torch", "monai", "nibabel", "gdown", "SimpleITK", "einops",
        "tqdm", "skimage", "matplotlib", "numpy", "pandas"]

for lib in libs:
    try:
        m = importlib.import_module(lib)
        print(f"✅ {lib:15s} {getattr(m, '__version__', '(no version attr)')}")
    except Exception as e:
        print(f"❌ {lib:15s} FAILED: {e}")

import torch
print("\nCUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("⚠️ No GPU detected — go to Runtime > Change runtime type > GPU")

import os, glob, json, zipfile, random, shutil, math, time, re, warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import nibabel as nib
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from monai.networks.nets import SwinUNETR
from monai.losses import DiceCELoss
from monai.metrics import DiceMetric, MeanIoU, ConfusionMatrixMetric
from monai.transforms import (
    Compose, RandFlipd, RandRotate90d, RandGaussianNoised,
    RandAdjustContrastd, RandShiftIntensityd
)
from monai.utils import set_determinism

set_determinism(seed=42)
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

print("Imports OK")

import os

CHECKPOINT_DIR = "/content/SwinUNETR_BraTS_checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
print("Checkpoints will be saved to:", CHECKPOINT_DIR)
print("⚠️ This is local to the Colab session — download results at the end or they'll be lost when the runtime resets.")

import glob, zipfile, gdown

DRIVE_FOLDER_URL = "https://drive.google.com/drive/folders/1ypN7aOv1PBff5QCY4D7oynZpLk37nk72"
DOWNLOAD_DIR = "/content/drive_download"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

gdown.download_folder(url=DRIVE_FOLDER_URL, output=DOWNLOAD_DIR, quiet=False, use_cookies=False)

zip_candidates = glob.glob(os.path.join(DOWNLOAD_DIR, "**", "*.zip"), recursive=True)
if not zip_candidates:
    raise FileNotFoundError(
        "No .zip found. Most likely the folder isn't shared publicly — "
        "right-click it in Drive > Share > General access > 'Anyone with the link', then rerun this cell."
    )
ZIP_PATH = zip_candidates[0]
print("Found zip:", ZIP_PATH)

EXTRACT_DIR = "/content/brats_extracted"
os.makedirs(EXTRACT_DIR, exist_ok=True)
with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
    zf.extractall(EXTRACT_DIR)
print("Extracted to:", EXTRACT_DIR)

def find_patient_dirs(root):
    patient_dirs = []
    for dirpath, dirnames, filenames in os.walk(root):
        nii_files = [f for f in filenames if f.endswith(".nii") or f.endswith(".nii.gz")]
        if len(nii_files) >= 2:
            patient_dirs.append(dirpath)
    return sorted(patient_dirs)

patient_dirs = find_patient_dirs(EXTRACT_DIR)
print(f"Detected {len(patient_dirs)} patient folders")
if patient_dirs:
    print("Example folder:", patient_dirs[0])
    print("Example files:", os.listdir(patient_dirs[0]))

CONFIG = {
    "train_frac": 0.90,
    "test_frac": 0.10,
    "slice_margin": 30,
    "img_size": 160,
    "modalities": ["flair", "t1ce", "t1", "t2"],
    "seg_suffix": "seg",
    "batch_size": 4,
    "num_workers": 2,
    "epochs": 40,
    "lr": 3e-4,
    "weight_decay": 1e-5,
    "early_stop_patience": 40,
    "num_classes": 4,
    "seed": 42,
    "class_names": ["Background", "Tumor Core", "Edema", "Enhancing Tumor"],
}
assert abs(CONFIG["train_frac"] + CONFIG["test_frac"] - 1.0) < 1e-6
print(json.dumps(CONFIG, indent=2))

def match_modality_files(patient_dir, config):
    files = [f for f in os.listdir(patient_dir) if f.endswith(".nii") or f.endswith(".nii.gz")]
    found = {}
    for key in config["modalities"] + [config["seg_suffix"]]:
        pattern = re.compile(rf"_{key}\.nii(\.gz)?$", re.IGNORECASE)
        matches = [f for f in files if pattern.search(f)]
        if not matches:
            matches = [f for f in files if f.lower().startswith(key.lower())]
        found[key] = os.path.join(patient_dir, matches[0]) if matches else None
    return found

patient_records = []
for pdir in patient_dirs:
    pid = os.path.basename(pdir)
    fmap = match_modality_files(pdir, CONFIG)
    if all(fmap.get(m) for m in CONFIG["modalities"]) and fmap.get(CONFIG["seg_suffix"]):
        patient_records.append({"patient_id": pid, "dir": pdir, **fmap})
    else:
        print(f"⚠️ Skipping {pid}: missing files -> {fmap}")

print(f"Usable patients: {len(patient_records)} / {len(patient_dirs)}")

random.shuffle(patient_records)
n = len(patient_records)
n_train = int(n * CONFIG["train_frac"])

train_patients = patient_records[:n_train]
test_patients  = patient_records[n_train:]

print(f"Train: {len(train_patients)}  Test: {len(test_patients)}")

split_df = pd.DataFrame([
    {"patient_id": p["patient_id"], "split": s}
    for s, plist in [("train", train_patients), ("test", test_patients)]
    for p in plist
])
split_df.to_csv(os.path.join(CHECKPOINT_DIR, "patient_split.csv"), index=False)
split_df.head()

def build_slice_index(patient_list, config):
    index = []
    for p in patient_list:
        seg_img = nib.load(p[config["seg_suffix"]])
        depth = seg_img.shape[2]
        margin = config["slice_margin"]
        lo, hi = margin, depth - margin
        if hi <= lo:
            print(f"⚠️ {p['patient_id']}: depth {depth} too small for margin {margin}, skipping")
            continue
        for s in range(lo, hi):
            index.append({**p, "slice_idx": s})
    return index

train_slices = build_slice_index(train_patients, CONFIG)
test_slices  = build_slice_index(test_patients, CONFIG)

print(f"Slices -> train: {len(train_slices)}  test: {len(test_slices)}")

import cv2

def remap_mask(mask):
    remapped = np.zeros_like(mask, dtype=np.int64)
    remapped[mask == 1] = 1
    remapped[mask == 2] = 2
    remapped[mask == 4] = 3
    return remapped

def normalize_slice(img):
    img = img.astype(np.float32)
    nz = img[img > 0]
    if nz.size > 0:
        mean, std = nz.mean(), nz.std() + 1e-8
        img = (img - mean) / std
    img = np.clip(img, -5, 5)
    img = (img - img.min()) / (img.max() - img.min() + 1e-8)
    return img

def resize_arr(arr, size, is_mask=False):
    interp = cv2.INTER_NEAREST if is_mask else cv2.INTER_LINEAR
    return cv2.resize(arr.astype(np.float32), (size, size), interpolation=interp)

print("Helpers ready")

from tqdm import tqdm

PREPROC_DIR = "/content/preprocessed"
os.makedirs(PREPROC_DIR, exist_ok=True)

def preprocess_split(slice_list, split_name, config):
    out_dir = os.path.join(PREPROC_DIR, split_name)
    os.makedirs(out_dir, exist_ok=True)
    manifest = []

    cur_pid = None
    stack = None
    seg = None

    for rec in tqdm(slice_list, desc=f"Preprocessing {split_name}"):
        pid, s = rec["patient_id"], rec["slice_idx"]

        if pid != cur_pid:
            mods = [nib.load(rec[m]).get_fdata() for m in config["modalities"]]
            seg = nib.load(rec[config["seg_suffix"]]).get_fdata()
            stack = np.stack(mods, axis=0)
            cur_pid = pid

        img_slice = stack[:, :, :, s]
        mask_slice = remap_mask(seg[:, :, s])

        size = config["img_size"]
        img_slice = np.stack(
            [resize_arr(normalize_slice(img_slice[c]), size) for c in range(img_slice.shape[0])],
            axis=0
        ).astype(np.float16)
        mask_slice = resize_arr(mask_slice.astype(np.float32), size, is_mask=True).astype(np.uint8)

        fname = f"{pid}_slice{s:04d}.npz"
        fpath = os.path.join(out_dir, fname)
        np.savez(fpath, image=img_slice, label=mask_slice)
        manifest.append({"patient_id": pid, "slice_idx": s, "path": fpath})

    return manifest

train_manifest = preprocess_split(train_slices, "train", CONFIG)
test_manifest  = preprocess_split(test_slices, "test", CONFIG)

print(f"Preprocessed -> train: {len(train_manifest)}  test: {len(test_manifest)}")

from monai.transforms import (
    Compose, RandFlipd, RandRotate90d, RandGaussianNoised,
    RandAdjustContrastd, RandShiftIntensityd
)

train_transforms = Compose([
    RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0),
    RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=1),
    RandRotate90d(keys=["image", "label"], prob=0.5, max_k=3),
    RandGaussianNoised(keys=["image"], prob=0.2, std=0.02),
    RandAdjustContrastd(keys=["image"], prob=0.2, gamma=(0.8, 1.2)),
    RandShiftIntensityd(keys=["image"], prob=0.2, offsets=0.05),
])

class FastSliceDataset(Dataset):
    def __init__(self, manifest, transforms=None):
        self.manifest = manifest
        self.transforms = transforms

    def __len__(self):
        return len(self.manifest)

    def __getitem__(self, idx):
        rec = self.manifest[idx]
        data = np.load(rec["path"])
        image = torch.from_numpy(data["image"].astype(np.float32))
        label = torch.from_numpy(data["label"].astype(np.int64)).unsqueeze(0)

        sample = {"image": image, "label": label}
        if self.transforms:
            sample = self.transforms(sample)

        sample["label"] = sample["label"].squeeze(0)
        sample["patient_id"] = rec["patient_id"]
        sample["slice_idx"] = rec["slice_idx"]
        return sample

print("Fast dataset class ready")

train_ds = FastSliceDataset(train_manifest, transforms=train_transforms)
test_ds  = FastSliceDataset(test_manifest, transforms=None)

train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True,
                           num_workers=2, pin_memory=True, drop_last=True,
                           persistent_workers=True, prefetch_factor=4)
test_loader  = DataLoader(test_ds, batch_size=CONFIG["batch_size"], shuffle=False,
                           num_workers=2, pin_memory=True,
                           persistent_workers=True, prefetch_factor=4)

print(f"Batches -> train: {len(train_loader)}  test: {len(test_loader)}")

batch = next(iter(train_loader))
print("image batch:", batch["image"].shape, " label batch:", batch["label"].shape)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device, torch.cuda.get_device_name(0) if torch.cuda.is_available() else "")

model = SwinUNETR(
    img_size=(CONFIG["img_size"], CONFIG["img_size"]),
    in_channels=len(CONFIG["modalities"]),
    out_channels=CONFIG["num_classes"],
    feature_size=48,
    spatial_dims=2,
    use_checkpoint=False,
).to(device)

n_params = sum(p.numel() for p in model.parameters())
print(f"SwinUNETR built — {n_params/1e6:.2f}M parameters")

loss_fn = DiceCELoss(to_onehot_y=True, softmax=True, include_background=True)
optimizer = torch.optim.AdamW(model.parameters(), lr=CONFIG["lr"], weight_decay=CONFIG["weight_decay"])

from torch.optim.lr_scheduler import LambdaLR, CosineAnnealingLR, SequentialLR

warmup_epochs = 5
warmup_scheduler = LambdaLR(optimizer, lr_lambda=lambda e: (e + 1) / warmup_epochs)
cosine_scheduler = CosineAnnealingLR(optimizer, T_max=CONFIG["epochs"] - warmup_epochs)
scheduler = SequentialLR(
    optimizer,
    schedulers=[warmup_scheduler, cosine_scheduler],
    milestones=[warmup_epochs],
)

scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available())
print(f"Loss / optimizer / scheduler ready ({warmup_epochs}-epoch warmup + cosine decay over "
      f"{CONFIG['epochs'] - warmup_epochs} epochs)")

dice_metric = DiceMetric(include_background=True, reduction="mean_batch")
iou_metric = MeanIoU(include_background=False, reduction="mean_batch")
cm_metric = ConfusionMatrixMetric(include_background=False, metric_name=["precision", "recall"], reduction="mean_batch")

def one_hot(labels, num_classes):
    return F.one_hot(labels, num_classes).permute(0, 3, 1, 2).float()

def compute_metrics(pred_logits, labels, num_classes):
    pred = torch.argmax(pred_logits, dim=1)
    pred_oh = one_hot(pred, num_classes)
    label_oh = one_hot(labels, num_classes)
    dice_metric(y_pred=pred_oh, y=label_oh)
    iou_metric(y_pred=pred_oh, y=label_oh)
    cm_metric(y_pred=pred_oh, y=label_oh)

def accuracy_from_logits(pred_logits, labels):
    pred = torch.argmax(pred_logits, dim=1)
    correct = (pred == labels).sum().item()
    total = labels.numel()
    return correct, total

def aggregate_reset(*metrics):
    results = [m.aggregate() for m in metrics]
    for m in metrics:
        m.reset()
    return results

print("Metrics ready")

from google.colab import files
print("Select your downloaded best_model.pt file:")
uploaded = files.upload()

UPLOADED_CKPT_PATH = list(uploaded.keys())[0]
ckpt_check = torch.load(UPLOADED_CKPT_PATH, map_location="cpu")

print("Checkpoint's actual recorded epoch:", ckpt_check["epoch"])
print("Checkpoint's Overall Dice:", ckpt_check["overall_dice"])

RESUME_START_EPOCH = ckpt_check["epoch"] + 1  # automatically continues from wherever this checkpoint left off

model.load_state_dict(ckpt_check["model_state"])
best_dice = ckpt_check["overall_dice"]
print(f"✅ Loaded model weights (checkpoint's own epoch label was {ckpt_check['epoch']})")
print(f"   Continuing the epoch counter from {RESUME_START_EPOCH} onward")

# Fast-forward the LR scheduler so it isn't back at epoch-1 LR
for _ in range(RESUME_START_EPOCH - 1):
    scheduler.step()

patience_counter = 0
history = {"train_loss": [], "overall_dice": [], "train_iou": [], "accuracy": [], "epoch_time_sec": []}
for cname in CONFIG["class_names"]:
    history[f"dice_{cname}"] = []

BEST_CKPT_LOCAL = "/content/best_model.pt"
BEST_CKPT_DRIVE = os.path.join(CHECKPOINT_DIR, "best_model.pt")

def download_best_model():
    if os.path.exists(BEST_CKPT_LOCAL):
        try:
            from google.colab import files as colab_files
            print("Downloading best model checkpoint...")
            colab_files.download(BEST_CKPT_LOCAL)
        except ImportError:
            print(f"Not running in Colab — best model saved locally at: {BEST_CKPT_LOCAL}")
    else:
        print("No best model was saved yet — nothing to download.")

total_train_start = time.time()
stop_reason = "completed all epochs"
epoch = RESUME_START_EPOCH

try:
    for epoch in range(RESUME_START_EPOCH, CONFIG["epochs"] + 1):
        t0 = time.time()
        model.train()
        running_loss = 0.0
        correct_px, total_px = 0, 0
        dice_metric.reset(); iou_metric.reset()

        for batch in tqdm(train_loader, desc=f"Epoch {epoch} Training"):
            images = batch["image"].to(device)
            labels = batch["label"].to(device)
            optimizer.zero_grad()
            with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
                outputs = model(images)
                loss = loss_fn(outputs, labels.unsqueeze(1))
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            running_loss += loss.item() * images.size(0)

            compute_metrics(outputs.detach().float(), labels, CONFIG["num_classes"])
            c, t = accuracy_from_logits(outputs.detach().float(), labels)
            correct_px += c
            total_px += t

        train_loss = running_loss / len(train_ds)
        scheduler.step()

        class_dice, train_iou_c = aggregate_reset(dice_metric, iou_metric)
        overall_dice = class_dice.mean().item()
        train_iou = train_iou_c.mean().item()
        accuracy = correct_px / total_px

        epoch_time = time.time() - t0

        history["train_loss"].append(train_loss)
        history["overall_dice"].append(overall_dice)
        history["train_iou"].append(train_iou)
        history["accuracy"].append(accuracy)
        history["epoch_time_sec"].append(epoch_time)
        for i, cname in enumerate(CONFIG["class_names"]):
            history[f"dice_{cname}"].append(class_dice[i].item())

        dice_str = " | ".join(
            f"Dice({cname}) {class_dice[i].item():.4f}" for i, cname in enumerate(CONFIG["class_names"])
        )
        print(f"Epoch {epoch:03d}/{CONFIG['epochs']} | Loss {train_loss:.4f} | "
              f"{dice_str} | Overall Dice {overall_dice:.4f} | "
              f"Accuracy {accuracy:.4f} | Time {epoch_time:.1f}s")

        if overall_dice > best_dice:
            best_dice = overall_dice
            patience_counter = 0
            torch.save({
                "model_state": model.state_dict(),
                "epoch": epoch,
                "overall_dice": overall_dice,
                "class_dice": {cname: class_dice[i].item() for i, cname in enumerate(CONFIG["class_names"])},
                "accuracy": accuracy,
                "config": CONFIG,
            }, BEST_CKPT_LOCAL)
            shutil.copy(BEST_CKPT_LOCAL, BEST_CKPT_DRIVE) if os.path.isdir(CHECKPOINT_DIR) else None
            print(f"  ✅ New best model (Overall Dice={best_dice:.4f}) saved")
        else:
            patience_counter += 1
            if patience_counter >= CONFIG["early_stop_patience"]:
                stop_reason = f"early stopped at epoch {epoch} (no improvement for {CONFIG['early_stop_patience']} epochs)"
                print(f"⏹ {stop_reason}")
                break

except KeyboardInterrupt:
    stop_reason = "manually interrupted by user"
    print(f"\n⚠️ Training interrupted manually — downloading best model saved so far...")

except torch.cuda.OutOfMemoryError as e:
    stop_reason = "stopped: GPU ran out of memory (CUDA OOM)"
    torch.cuda.empty_cache()
    print(f"\n🛑 GPU ran out of memory at epoch {epoch}.")
    print("   Downloading the best model saved so far.")
    print("   To avoid this next run: lower CONFIG['batch_size'], lower CONFIG['img_size'], or set use_checkpoint=True in the model.")

except RuntimeError as e:
    if "out of memory" in str(e).lower():
        stop_reason = "stopped: GPU ran out of memory (CUDA OOM)"
        torch.cuda.empty_cache()
        print(f"\n🛑 GPU ran out of memory at epoch {epoch}.")
        print("   Downloading the best model saved so far.")
        print("   To avoid this next run: lower CONFIG['batch_size'], lower CONFIG['img_size'], or set use_checkpoint=True in the model.")
    else:
        stop_reason = f"stopped due to a runtime error: {e}"
        print(f"\n⚠️ Training stopped due to an error ({e}) — downloading best model saved so far...")
        raise

except Exception as e:
    stop_reason = f"stopped due to an error: {e}"
    print(f"\n⚠️ Training stopped due to an error ({e}) — downloading best model saved so far...")
    raise

finally:
    total_train_time = time.time() - total_train_start
    print(f"\nTraining ended — reason: {stop_reason}")
    print(f"Best Overall Dice: {best_dice:.4f}" if best_dice > -1.0 else "No epoch improved on the initial best_dice.")
    print(f"Total training time: {total_train_time/60:.1f} minutes ({total_train_time:.1f}s)")
    download_best_model()

import pandas as pd
from IPython.display import display

model.eval()
dice_metric.reset(); iou_metric.reset(); cm_metric.reset()
correct_px, total_px = 0, 0

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Final Test Evaluation"):
        images = batch["image"].to(device)
        labels = batch["label"].to(device)
        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
            outputs = model(images)
        compute_metrics(outputs.float(), labels, CONFIG["num_classes"])
        c, t = accuracy_from_logits(outputs.float(), labels)
        correct_px += c
        total_px += t

test_class_dice, test_iou_c, test_cm_result = aggregate_reset(dice_metric, iou_metric, cm_metric)
test_precision_c, test_recall_c = test_cm_result

test_overall_dice = test_class_dice.mean().item()
test_iou = test_iou_c.mean().item()
test_precision = test_precision_c.mean().item()
test_recall = test_recall_c.mean().item()
test_accuracy = correct_px / total_px

train_dice_final = history["overall_dice"][-1]
train_acc_final = history["accuracy"][-1]
total_time_sec = sum(history["epoch_time_sec"])

print(f"Train Dice: {train_dice_final:.4f}")
print(f"Train Accuracy: {train_acc_final:.4f}\n")

test_summary_df = pd.DataFrame({
    "Metric": ["Accuracy", "Dice Score", "IoU", "Precision", "Recall"],
    "Score": [
        f"{test_accuracy:.4f}",
        f"{test_overall_dice:.4f}",
        f"{test_iou:.4f}",
        f"{test_precision:.4f}",
        f"{test_recall:.4f}",
    ],
})
print("Test Set Result:")
display(test_summary_df)

class_dice_map = {cname: test_class_dice[i].item() for i, cname in enumerate(CONFIG["class_names"])}
per_class_df = pd.DataFrame({
    "Region": ["Background", "Enhancing Tumor", "Tumor Core", "Edema"],
    "Dice Score": [
        f"{class_dice_map['Background']:.4f}",
        f"{class_dice_map['Enhancing Tumor']:.4f}",
        f"{class_dice_map['Tumor Core']:.4f}",
        f"{class_dice_map['Edema']:.4f}",
    ],
})
print("\nPer-Class Dice:")
display(per_class_df)

print(f"\nTotal Training Time: {total_time_sec/60:.1f} minutes ({total_time_sec:.1f} seconds)")

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import torch
import random

# Custom colormap for masks: 0=Background, 1=Tumor Core, 2=Edema, 3=Enhancing Tumor
mask_colors = ["#0b1547", "#f4d35e", "#4fc3d9", "#e63946"]
mask_cmap = mcolors.ListedColormap(mask_colors)
mask_norm = mcolors.BoundaryNorm(boundaries=[-0.5, 0.5, 1.5, 2.5, 3.5], ncolors=4)

def pick_sample_indices(dataset, num_tumor=2, num_background=1):
    tumor_idx, bg_idx = [], []
    indices = list(range(len(dataset)))
    random.shuffle(indices)
    for i in indices:
        rec = dataset.manifest[i]
        data = np.load(rec["path"])
        if (data["label"] > 0).any():
            if len(tumor_idx) < num_tumor:
                tumor_idx.append(i)
        else:
            if len(bg_idx) < num_background:
                bg_idx.append(i)
        if len(tumor_idx) >= num_tumor and len(bg_idx) >= num_background:
            break
    return tumor_idx + bg_idx

sample_indices = pick_sample_indices(test_ds, num_tumor=2, num_background=1)

modality_names = CONFIG["modalities"]  # ["flair", "t1ce", "t1", "t2"]
modality_titles = {"flair": "FLAIR", "t1ce": "T1CE", "t1": "T1", "t2": "T2"}

model.eval()
n_rows = len(sample_indices)
n_cols = len(modality_names) + 2  # + Ground Truth + Predicted

fig, axes = plt.subplots(n_rows, n_cols, figsize=(4 * n_cols, 4 * n_rows))
if n_rows == 1:
    axes = axes.reshape(1, -1)

with torch.no_grad():
    for row, idx in enumerate(sample_indices):
        sample = test_ds[idx]
        image = sample["image"].unsqueeze(0).to(device)   # (1, C, H, W)
        label = sample["label"].numpy()

        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
            output = model(image)
        pred = torch.argmax(output, dim=1).squeeze(0).cpu().numpy()

        image_np = sample["image"].numpy()  # (C, H, W)

        for col, mod in enumerate(modality_names):
            axes[row, col].imshow(image_np[col], cmap="gray")
            axes[row, col].set_title(modality_titles.get(mod, mod), fontsize=12)
            axes[row, col].axis("off")

        gt_col = len(modality_names)
        pred_col = len(modality_names) + 1

        axes[row, gt_col].imshow(image_np[0], cmap="gray")
        axes[row, gt_col].imshow(label, cmap=mask_cmap, norm=mask_norm, alpha=0.5)
        axes[row, gt_col].set_title("Ground Truth Mask", fontsize=12)
        axes[row, gt_col].axis("off")

        axes[row, pred_col].imshow(image_np[0], cmap="gray")
        axes[row, pred_col].imshow(pred, cmap=mask_cmap, norm=mask_norm, alpha=0.5)
        axes[row, pred_col].set_title("Predicted Mask", fontsize=12)
        axes[row, pred_col].axis("off")

plt.suptitle("SwinUNETR — Multi-Modality Segmentation Results", fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("/content/segmentation_results.png", dpi=150, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("/content/segmentation_results.png")